import { Router, type IRouter } from "express";
import { requireAuth } from "../middleware/auth";
import { requireTenant } from "../middleware/tenant";
import { licenseCheck } from "../middleware/license-check";
import healthRouter from "./health";
import authRouter from "./auth";
import registerRouter from "./register";
import callsRouter from "./calls";
import contactsRouter from "./contacts";
import tasksRouter from "./tasks";
import messagesRouter from "./messages";
import dashboardRouter from "./dashboard";
import aiAnalysisRouter from "./ai-analysis";
import workspaceRouter from "./workspace";
import integrationsRouter from "./integrations";
import checkinsRouter from "./checkins";
import aiAgentsRouter from "./ai-agents";
import backupsRouter from "./backups";
import googleOAuthRouter from "./google-oauth";
import calendarRouter from "./calendar";
import auditRouter from "./audit";
import searchRouter from "./search";
import exportRouter from "./export";
import automationsRouter from "./automations";
import performanceRouter from "./performance";
import subscriptionsRouter from "./subscriptions";
import organisationsRouter from "./organisations";
import adminReportsRouter from "./admin-reports";
import billingRouter from "./billing";
import legalRouter from "./legal";
import googleDriveBackupRouter from "./google-drive-backup";
import securityRouter from "./security";
import googleWorkspaceRouter from "./google-workspace";
import mathRouter from "./math";
import dataProtectionRouter from "./data-protection";
import documentAiRouter from "./document-ai";
import mySubscriptionRouter from "./my-subscription";
import smartReportsRouter from "./smart-reports";
import bulkOperationsRouter from "./bulk-operations";
import licenseManagementRouter from "./license-management";
import aiCommandantRouter from "./ai-commandant";
import faceRecognitionRouter from "./face-recognition";
import telephonyRouter, { telephonyWebhookRouter } from "./telephony";
import voiceCommandRouter from "./voice-command";
import invitationsRouter from "./invitations";
const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(registerRouter);
router.use(telephonyWebhookRouter);

router.get("/invitations/verify/:token", (req, res, next) => { invitationsRouter(req, res, next); });
router.post("/invitations/accept/:token", (req, res, next) => { invitationsRouter(req, res, next); });

router.use(requireAuth);
router.use(requireTenant);

router.use(mySubscriptionRouter);
router.use(licenseCheck);

router.use(callsRouter);
router.use(contactsRouter);
router.use(tasksRouter);
router.use(messagesRouter);
router.use(dashboardRouter);
router.use(aiAnalysisRouter);
router.use(aiAgentsRouter);
router.use(calendarRouter);
router.use(auditRouter);
router.use(searchRouter);
router.use(exportRouter);
router.use(automationsRouter);
router.use(subscriptionsRouter);
router.use("/workspace", workspaceRouter);
router.use("/workspace", backupsRouter);
router.use("/integrations", integrationsRouter);
router.use("/google-oauth", googleOAuthRouter);
router.use(checkinsRouter);
router.use(performanceRouter);
router.use(organisationsRouter);
router.use(adminReportsRouter);
router.use(billingRouter);
router.use(legalRouter);
router.use(googleDriveBackupRouter);
router.use(securityRouter);
router.use(googleWorkspaceRouter);
router.use(mathRouter);
router.use(dataProtectionRouter);
router.use(documentAiRouter);
router.use(smartReportsRouter);
router.use(bulkOperationsRouter);
router.use(licenseManagementRouter);
router.use(aiCommandantRouter);
router.use("/face", faceRecognitionRouter);
router.use(telephonyRouter);
router.use(voiceCommandRouter);
router.use(invitationsRouter);

export default router;
